language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
env:
  matrix:
    - "MASTER=false"
    - "MASTER=true"
git:
  depth: 10
before_install:
  - "npm config set loglevel error"
before_script:
  - "[ $MASTER == false ] || sh ./symlink.sh"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@2.11.x && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
    - env: "MASTER=true"
notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
